services:

  mysql:
    image: mysql:8.0
    container_name: worshiphub-mysql
    restart: always
    env_file:
      - .env
    command: --max_connections=50
    mem_limit: 350m
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - worshiphub-network

  worshiphub-api:
    image: ghcr.io/lucaspccamara/worshiphub-api:latest
    container_name: worshiphub-api
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    mem_limit: 400m
    networks:
      - worshiphub-network

  nginx:
    image: nginx:alpine
    container_name: worshiphub-nginx
    restart: always
    ports:
      - "80:80"
    mem_limit: 80m
    volumes:
      - ./frontend-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - worshiphub-api
    networks:
      - worshiphub-network

volumes:
  mysql_data:
    external: true
    name: worshiphub_mysql_data

networks:
  worshiphub-network: